# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drotvaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from entities.rud import Rud
from entities.csomopont import Csomopont
import sqlite3

drotvazlista: list = []
rud: list = []
csomopont: list = []

class vaz:
    def __init__(self, projekt, azonosito):
        self.projekt = projekt
        self.azonosito = azonosito

class Ui_Drotvaz(object):
    def setupUi(self, Drotvaz):
        Drotvaz.setObjectName("Drotvaz")
        Drotvaz.resize(950, 600)
        self.nezet = QtWidgets.QGraphicsView(Drotvaz)
        self.nezet.setGeometry(QtCore.QRect(10, 70, 500, 500))
        self.nezet.setObjectName("nezet")
        self.label = QtWidgets.QLabel(Drotvaz)
        self.label.setGeometry(QtCore.QRect(6, 580, 61, 20))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Drotvaz)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Drotvaz)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 71, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.projekt_lista = QtWidgets.QComboBox(Drotvaz)
        self.projekt_lista.setGeometry(QtCore.QRect(80, 10, 291, 22))
        self.projekt_lista.setObjectName("projekt_lista")
        self.drotvazak = QtWidgets.QComboBox(Drotvaz)
        self.drotvazak.setGeometry(QtCore.QRect(79, 40, 291, 22))
        self.drotvazak.setObjectName("drotvazak")
        self.projekt_kivalaszto = QtWidgets.QPushButton(Drotvaz)
        self.projekt_kivalaszto.setGeometry(QtCore.QRect(404, 10, 91, 23))

        # A projekt-hez tartozó váztervek kiválasztása
        self.projekt_kivalaszto.clicked.connect(self.drotvaz_tetelek)
        #
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.projekt_kivalaszto.setFont(font)
        self.projekt_kivalaszto.setObjectName("projekt_kivalaszto")
        self.drotvaz_kivalaszt = QtWidgets.QPushButton(Drotvaz)
        self.drotvaz_kivalaszt.setGeometry(QtCore.QRect(404, 40, 91, 23))

        # A vázterv rudainak kiválasztása
        self.drotvaz_kivalaszt.clicked.connect(self.rud_tetelek)
        #
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.drotvaz_kivalaszt.setFont(font)
        self.drotvaz_kivalaszt.setObjectName("drotvaz_kivalaszt")
        self.horizontalSlider = QtWidgets.QSlider(Drotvaz)
        self.horizontalSlider.setGeometry(QtCore.QRect(70, 580, 441, 20))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.rudak = QtWidgets.QTableWidget(Drotvaz)
        self.rudak.setGeometry(QtCore.QRect(520, 70, 421, 501))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        self.rudak.setFont(font)
        self.rudak.setRowCount(0)
        self.rudak.setObjectName("rudak")
        self.rudak.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.rudak.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rudak.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rudak.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rudak.setHorizontalHeaderItem(3, item)

        self.rudkivalaszto = QtWidgets.QPushButton(Drotvaz)
        self.rudkivalaszto.setGeometry(QtCore.QRect(829, 575, 111, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.rudkivalaszto.setFont(font)
        self.rudkivalaszto.setObjectName("rudkivalaszto")
        self.alaphelyzet = QtWidgets.QPushButton(Drotvaz)
        self.alaphelyzet.setGeometry(QtCore.QRect(520, 10, 121, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.alaphelyzet.setFont(font)
        self.alaphelyzet.setObjectName("alaphelyzet")
        self.Kodosito = QtWidgets.QPushButton(Drotvaz)
        self.Kodosito.setGeometry(QtCore.QRect(520, 40, 121, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.Kodosito.setFont(font)
        self.Kodosito.setObjectName("Kodosito")
        self.pngkep = QtWidgets.QPushButton(Drotvaz)
        self.pngkep.setGeometry(QtCore.QRect(660, 10, 111, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.pngkep.setFont(font)
        self.pngkep.setObjectName("pngkep")
        self.vastagvonalak = QtWidgets.QPushButton(Drotvaz)
        self.vastagvonalak.setGeometry(QtCore.QRect(660, 40, 111, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        self.vastagvonalak.setFont(font)
        self.vastagvonalak.setObjectName("vastagvonalak")
        self.loadprojekt()
        self.retranslateUi(Drotvaz)
        QtCore.QMetaObject.connectSlotsByName(Drotvaz)

    def loadprojekt(self):
        con = sqlite3.connect('vazdata.db')
        cur = con.cursor()
        sql = 'select distinct projekt from vazcsomopont'
        for row in cur.execute(sql):
            self.projekt_lista.addItem(str(row[0]))
        self.drotvaz_tetelek()

    def drotvaz_tetelek(self):
        self.drotvazak.clear()
        con = sqlite3.connect('vazdata.db')
        cur = con.cursor()
        sql = 'select distinct azonosito from vazcsomopont '
        sql = sql + 'where projekt = "' + str(self.projekt_lista.currentText()) + '" '
        sql = sql + 'order by azonosito'
        # print(sql)
        for row in cur.execute(sql):
            self.drotvazak.addItem(str(row[0]))
    
    def rud_tetelek(self):
        con = sqlite3.connect('vazdata.db')
        cur = con.cursor()
        sql = 'select id,kezdocsp,vegecsp,piros,zold,kek from vazrud '
        sql = sql + 'where projekt = "' + str(self.projekt_lista.currentText()) + '" '
        sql = sql + 'and azonosito = "' + str(self.drotvazak.currentText()) + '" '
        sql = sql + 'order by id'
        #print(sql)
        for row in cur.execute(sql):
            r = Rud(id, str(self.projekt_lista.currentText()),
                    str(self.drotvazak.currentText()),
                    str(row[1]), str(row[2]), '', str(row[3]),
                    str(row[4]), str(row[5]), 0, '', 0)
            rud.append(r)
        sql = 'select id,csomopont,x,y,z from vazcsomopont '
        sql = sql + 'where projekt = "' + str(self.projekt_lista.currentText()) + '" '
        sql = sql + 'and azonosito = "' + str(self.drotvazak.currentText()) + '" '
        sql = sql + 'order by csomopont'
        #print(sql)
        for row in cur.execute(sql):
            c = Csomopont(id, str(self.projekt_lista.currentText()),
                          str(self.drotvazak.currentText()),
                          str(row[1]), str(row[2]), str(row[3]), str(row[4]), 0)
            csomopont.append(c)
        # A táblázat feltöltés
        self.rudak.clear()
        sql = 'select count(*) from vazrud '
        sql = sql + 'where projekt = "' + str(self.projekt_lista.currentText()) + '" '
        sql = sql + 'and azonosito = "' + str(self.drotvazak.currentText()) + '" '
        #print(sql)
        self.sorok_szama = 0
        for row in cur.execute(sql):
            self.sorok_szama = row[0]
        # Row count
        self.rudak.setRowCount(self.sorok_szama)
        self.sorszam = -1
        for row in rud:
            self.sorszam = self.sorszam + 1
            item = QtWidgets.QTableWidgetItem(str(row.kezdocsp))
            item.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
            self.rudak.setItem(self.sorszam, 0, item)     # Kezdocsp
            item = QtWidgets.QTableWidgetItem(str(row.vegecsp))
            item.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
            self.rudak.setItem(self.sorszam, 1, item)     # Végecsp
            item = QtWidgets.QTableWidgetItem(str(row.piros))
            item.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
            self.rudak.setItem(self.sorszam, 2, item)     # Szín
            item = QtWidgets.QTableWidgetItem(str(row.mark))
            item.setTextAlignment(QtCore.Qt.AlignVCenter | QtCore.Qt.AlignHCenter)
            self.rudak.setItem(self.sorszam, 3, item)     # Mark

    def retranslateUi(self, Drotvaz):
        _translate = QtCore.QCoreApplication.translate
        Drotvaz.setWindowTitle(_translate("Drotvaz", "Rácsos szerkezetek drótvázainak megjelenítése"))
        self.label.setText(_translate("Drotvaz", "Eltolás"))
        self.label_2.setText(_translate("Drotvaz", "Projekt:"))
        self.label_3.setText(_translate("Drotvaz", "Drótváz:"))
        self.projekt_kivalaszto.setText(_translate("Drotvaz", "Kiválaszt"))
        self.drotvaz_kivalaszt.setText(_translate("Drotvaz", "Lássuk"))
        item = self.rudak.horizontalHeaderItem(0)
        item.setText(_translate("Drotvaz", "Kezdöcsp."))
        item = self.rudak.horizontalHeaderItem(1)
        item.setText(_translate("Drotvaz", "Végcsp."))
        item = self.rudak.horizontalHeaderItem(2)
        item.setText(_translate("Drotvaz", "Szín"))
        item = self.rudak.horizontalHeaderItem(3)
        item.setText(_translate("Drotvaz", "Kijelzés"))
        self.rudkivalaszto.setText(_translate("Drotvaz", "Megjelöl"))
        self.alaphelyzet.setText(_translate("Drotvaz", "Alaphelyzet"))
        self.Kodosito.setText(_translate("Drotvaz", "Ködös rajz"))
        self.pngkep.setText(_translate("Drotvaz", "PNG-kép"))
        self.vastagvonalak.setText(_translate("Drotvaz", "Vastag vonal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Drotvaz = QtWidgets.QDialog()
    ui = Ui_Drotvaz()
    ui.setupUi(Drotvaz)
    Drotvaz.show()
    sys.exit(app.exec_())
