package Entities;
// Generated 2014.03.09. 21:55:51 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Fajsuly generated by hbm2java
 */
public class Fajsuly  implements java.io.Serializable {


     private Integer id;
     private String megnevezes;
     private float fajsuly;
     private int rugmodulus;
     private Date felvitel;

    public Fajsuly() {
    }

    public Fajsuly(String megnevezes, float fajsuly, int rugmodulus, Date felvitel) {
       this.megnevezes = megnevezes;
       this.fajsuly = fajsuly;
       this.rugmodulus = rugmodulus;
       this.felvitel = felvitel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMegnevezes() {
        return this.megnevezes;
    }
    
    public void setMegnevezes(String megnevezes) {
        this.megnevezes = megnevezes;
    }
    public float getFajsuly() {
        return this.fajsuly;
    }
    
    public void setFajsuly(float fajsuly) {
        this.fajsuly = fajsuly;
    }
    public int getRugmodulus() {
        return this.rugmodulus;
    }
    
    public void setRugmodulus(int rugmodulus) {
        this.rugmodulus = rugmodulus;
    }
    public Date getFelvitel() {
        return this.felvitel;
    }
    
    public void setFelvitel(Date felvitel) {
        this.felvitel = felvitel;
    }




}


