package Entities;
// Generated 2014.03.09. 21:55:51 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Kontur generated by hbm2java
 */
public class Kontur implements java.io.Serializable {

    private Integer id;
    private String nev;    // A szelvény neve
    private int vonal;     // A vonal sorszáma 1-külső, 2 vagy több -> belső
    private int sorszam;   // Az elem sorszáma
    private int jelleg;    // Egyenes vagy görbe (E->1/G->2)
    private float x1;      // Vonal: x1, görbe: KözéppontX
    private float y1;      // Vonal: y1, görbe: KözéppontY
    private float x2;      // Vonal: x2, görbe: Sugárx
    private float y2;      // Vonal: y2, görbe: Sugáry
    private float r1;      // Vonal: 0, görbe: Kezdőszög
    private float r2;      // Vonal: 0, görbe: Végszög
    private int irany;     // A görbék rajzolásánál az irány (1->CCW,2->CW)
    private Date felvitel;
    
    public Kontur() {
    }

    public Kontur(String nev, int vonal, int sorszam, int jelleg, float x1, float y1, float x2, float y2, float r1, float r2, int irany, Date felvitel) {
        this.nev = nev;
        this.vonal = vonal;
        this.sorszam = sorszam;
        this.jelleg = jelleg;
        this.x1 = x1;
        this.y1 = y1;
        this.x2 = x2;
        this.y2 = y2;
        this.r1 = r1;
        this.r2 = r2;
        this.irany = irany;
        this.felvitel = felvitel;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNev() {
        return this.nev;
    }

    public void setNev(String nev) {
        this.nev = nev;
    }

    public int getVonal() {
        return this.vonal;
    }

    public void setVonal(int vonal) {
        this.vonal = vonal;
    }

    public int getSorszam() {
        return this.sorszam;
    }

    public void setSorszam(int sorszam) {
        this.sorszam = sorszam;
    }

    public int getJelleg() {
        return this.jelleg;
    }

    public void setJelleg(int jelleg) {
        this.jelleg = jelleg;
    }

    public float getX1() {
        return this.x1;
    }

    public void setX1(float x1) {
        this.x1 = x1;
    }

    public float getY1() {
        return this.y1;
    }

    public void setY1(float y1) {
        this.y1 = y1;
    }

    public float getX2() {
        return this.x2;
    }

    public void setX2(float x2) {
        this.x2 = x2;
    }

    public float getY2() {
        return this.y2;
    }

    public void setY2(float y2) {
        this.y2 = y2;
    }

    public float getR1() {
        return this.r1;
    }

    public void setR1(float r1) {
        this.r1 = r1;
    }

    public float getR2() {
        return this.r2;
    }

    public void setR2(float r2) {
        this.r2 = r2;
    }

    public int getIrany() {
        return this.irany;
    }

    public void setIrany(int irany) {
        this.irany = irany;
    }

    public Date getFelvitel() {
        return this.felvitel;
    }

    public void setFelvitel(Date felvitel) {
        this.felvitel = felvitel;
    }
    

}
