package Entities;
// Generated 2014.03.09. 21:55:51 by Hibernate Tools 3.6.0



/**
 * Mintacsp generated by hbm2java
 */
public class Mintacsp  implements java.io.Serializable {


     private Integer id;
     private int irany;
     private int csomopont;
     private float x;
     private float y;
     private float z;
     private int jellegxy;
     private int jellegyz;
     private int kezdcspxy;
     private int vegecspxy;
     private int kezdcspyz;
     private int vegecspyz;

    public Mintacsp() {
    }

    public Mintacsp(int irany, int csomopont, float x, float y, float z, int jellegxy, int jellegyz, int kezdcspxy, int vegecspxy, int kezdcspyz, int vegecspyz) {
       this.irany = irany;
       this.csomopont = csomopont;
       this.x = x;
       this.y = y;
       this.z = z;
       this.jellegxy = jellegxy;
       this.jellegyz = jellegyz;
       this.kezdcspxy = kezdcspxy;
       this.vegecspxy = vegecspxy;
       this.kezdcspyz = kezdcspyz;
       this.vegecspyz = vegecspyz;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIrany() {
        return this.irany;
    }
    
    public void setIrany(int irany) {
        this.irany = irany;
    }
    public int getCsomopont() {
        return this.csomopont;
    }
    
    public void setCsomopont(int csomopont) {
        this.csomopont = csomopont;
    }
    public float getX() {
        return this.x;
    }
    
    public void setX(float x) {
        this.x = x;
    }
    public float getY() {
        return this.y;
    }
    
    public void setY(float y) {
        this.y = y;
    }
    public float getZ() {
        return this.z;
    }
    
    public void setZ(float z) {
        this.z = z;
    }
    public int getJellegxy() {
        return this.jellegxy;
    }
    
    public void setJellegxy(int jellegxy) {
        this.jellegxy = jellegxy;
    }
    public int getJellegyz() {
        return this.jellegyz;
    }
    
    public void setJellegyz(int jellegyz) {
        this.jellegyz = jellegyz;
    }
    public int getKezdcspxy() {
        return this.kezdcspxy;
    }
    
    public void setKezdcspxy(int kezdcspxy) {
        this.kezdcspxy = kezdcspxy;
    }
    public int getVegecspxy() {
        return this.vegecspxy;
    }
    
    public void setVegecspxy(int vegecspxy) {
        this.vegecspxy = vegecspxy;
    }
    public int getKezdcspyz() {
        return this.kezdcspyz;
    }
    
    public void setKezdcspyz(int kezdcspyz) {
        this.kezdcspyz = kezdcspyz;
    }
    public int getVegecspyz() {
        return this.vegecspyz;
    }
    
    public void setVegecspyz(int vegecspyz) {
        this.vegecspyz = vegecspyz;
    }




}


