package Entities;
// Generated 2014.03.09. 21:55:51 by Hibernate Tools 3.6.0



/**
 * Mintarud generated by hbm2java
 */
public class Mintarud  implements java.io.Serializable {


     private Integer id;
     private int irany;
     private int tipus;
     private int verzio;
     private int kezdocsp;
     private int vegecsp;

    public Mintarud() {
    }

    public Mintarud(int irany, int tipus, int verzio, int kezdocsp, int vegecsp) {
       this.irany = irany;
       this.tipus = tipus;
       this.verzio = verzio;
       this.kezdocsp = kezdocsp;
       this.vegecsp = vegecsp;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIrany() {
        return this.irany;
    }
    
    public void setIrany(int irany) {
        this.irany = irany;
    }
    public int getTipus() {
        return this.tipus;
    }
    
    public void setTipus(int tipus) {
        this.tipus = tipus;
    }
    public int getVerzio() {
        return this.verzio;
    }
    
    public void setVerzio(int verzio) {
        this.verzio = verzio;
    }
    public int getKezdocsp() {
        return this.kezdocsp;
    }
    
    public void setKezdocsp(int kezdocsp) {
        this.kezdocsp = kezdocsp;
    }
    public int getVegecsp() {
        return this.vegecsp;
    }
    
    public void setVegecsp(int vegecsp) {
        this.vegecsp = vegecsp;
    }




}


