package Entities;
// Generated 2014.03.09. 21:55:51 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Racsalap generated by hbm2java
 */
public class Racsalap  implements java.io.Serializable {


     private Integer id;
     private String nev;
     private int szekcio;
     private int magassag;
     private int alsoszelxy;
     private int felsoszelxy;
     private int alsoszelyz;
     private int felsoszelyz;
     private int x;
     private int y;
     private int z;
     private int irany;
     private int teljes;
     private int eltolasxy;
     private int eltolasyz;
     private String nev1;
     private String nev2;
     private String nev3;
     private String nev4;
     private String nev5;
     private String nev6;
     private String nev7;
     private String nev8;
     private Date felvitel;

    public Racsalap() {
    }

    public Racsalap(String nev, int szekcio, int magassag, int alsoszelxy, int felsoszelxy, int alsoszelyz, int felsoszelyz, int x, int y, int z, int irany, int teljes, int eltolasxy, int eltolasyz, Date felvitel) {
       this.nev = nev;
       this.szekcio = szekcio;
       this.magassag = magassag;
       this.alsoszelxy = alsoszelxy;
       this.felsoszelxy = felsoszelxy;
       this.alsoszelyz = alsoszelyz;
       this.felsoszelyz = felsoszelyz;
       this.x = x;
       this.y = y;
       this.z = z;
       this.irany = irany;
       this.teljes = teljes;
       this.eltolasxy = eltolasxy;
       this.eltolasyz = eltolasyz;
       this.felvitel = felvitel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNev() {
        return this.nev;
    }
    
    public void setNev(String nev) {
        this.nev = nev;
    }
    public int getSzekcio() {
        return this.szekcio;
    }
    
    public void setSzekcio(int szekcio) {
        this.szekcio = szekcio;
    }
    public int getMagassag() {
        return this.magassag;
    }
    
    public void setMagassag(int magassag) {
        this.magassag = magassag;
    }
    public int getAlsoszelxy() {
        return this.alsoszelxy;
    }
    
    public void setAlsoszelxy(int alsoszelxy) {
        this.alsoszelxy = alsoszelxy;
    }
    public int getFelsoszelxy() {
        return this.felsoszelxy;
    }
    
    public void setFelsoszelxy(int felsoszelxy) {
        this.felsoszelxy = felsoszelxy;
    }
    public int getAlsoszelyz() {
        return this.alsoszelyz;
    }
    
    public void setAlsoszelyz(int alsoszelyz) {
        this.alsoszelyz = alsoszelyz;
    }
    public int getFelsoszelyz() {
        return this.felsoszelyz;
    }
    
    public void setFelsoszelyz(int felsoszelyz) {
        this.felsoszelyz = felsoszelyz;
    }
    public int getX() {
        return this.x;
    }
    
    public void setX(int x) {
        this.x = x;
    }
    public int getY() {
        return this.y;
    }
    
    public void setY(int y) {
        this.y = y;
    }
    public int getZ() {
        return this.z;
    }
    
    public void setZ(int z) {
        this.z = z;
    }
    public int getIrany() {
        return this.irany;
    }
    
    public void setIrany(int irany) {
        this.irany = irany;
    }
    public int getTeljes() {
        return this.teljes;
    }
    
    public void setTeljes(int teljes) {
        this.teljes = teljes;
    }
    public int getEltolasxy() {
        return this.eltolasxy;
    }
    
    public void setEltolasxy(int eltolasxy) {
        this.eltolasxy = eltolasxy;
    }
    public int getEltolasyz() {
        return this.eltolasyz;
    }
    
    public void setEltolasyz(int eltolasyz) {
        this.eltolasyz = eltolasyz;
    }
    public Date getFelvitel() {
        return this.felvitel;
    }
    
    public void setFelvitel(Date felvitel) {
        this.felvitel = felvitel;
    }

    public String getNev1() {
        return nev1;
    }

    public void setNev1(String nev1) {
        this.nev1 = nev1;
    }

    public String getNev2() {
        return nev2;
    }

    public void setNev2(String nev2) {
        this.nev2 = nev2;
    }

    public String getNev3() {
        return nev3;
    }

    public void setNev3(String nev3) {
        this.nev3 = nev3;
    }

    public String getNev4() {
        return nev4;
    }

    public void setNev4(String nev4) {
        this.nev4 = nev4;
    }

    public String getNev5() {
        return nev5;
    }

    public void setNev5(String nev5) {
        this.nev5 = nev5;
    }

    public String getNev6() {
        return nev6;
    }

    public void setNev6(String nev6) {
        this.nev6 = nev6;
    }

    public String getNev7() {
        return nev7;
    }

    public void setNev7(String nev7) {
        this.nev7 = nev7;
    }

    public String getNev8() {
        return nev8;
    }

    public void setNev8(String nev8) {
        this.nev8 = nev8;
    }




}


