package Entities;
// Generated 2014.03.09. 21:55:51 by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Szelveny generated by hbm2java
 */
public class Szelveny implements java.io.Serializable {

    private Integer id;
    private String nev;
    private String filenev;
    private float magassag;
    private float szelesseg;
    private float v;
    private float r;
    private float r1;
    private float r2;
    private float w;
    private float w1;
    private float u;
    private float u1;
    private float u2;
    private float z;
    private float c;
    private float h1;
    private float t;
    private float tgalfa;
    private float a;
    private float ex;
    private float ey;
    private float ix;
    private float kx;
    private float sx;
    private float inx;
    private float iy;
    private float ky;
    private float sy;
    private float iny;
    private float fmsuly;
    private String anyag;
    private String megnevezes;
    private String megjegyzes;
    private Date felvitel;    

    public Szelveny() {
    }

    public Szelveny(String nev, String filenev, float magassag, float szelesseg, float v, float r, float r1, float r2, float w, float w1, float u, float u1, float u2, float z, float c, float h1, float t, float tgalfa, float a, float ex, float ey, float ix, float kx, float sx, float inx, float iy, float ky, float sy, float iny, float fmsuly, String anyag, String megnevezes, Date felvitel) {
        this.nev = nev;
        this.filenev = filenev;
        this.magassag = magassag;
        this.szelesseg = szelesseg;
        this.v = v;
        this.r = r;
        this.r1 = r1;
        this.r2 = r2;
        this.w = w;
        this.w1 = w1;
        this.u = u;
        this.u1 = u1;
        this.u2 = u2;
        this.z = z;
        this.c = c;
        this.h1 = h1;
        this.t = t;
        this.tgalfa = tgalfa;
        this.a = a;
        this.ex = ex;
        this.ey = ey;
        this.ix = ix;
        this.kx = kx;
        this.sx = sx;
        this.inx = inx;
        this.iy = iy;
        this.ky = ky;
        this.sy = sy;
        this.iny = iny;
        this.fmsuly = fmsuly;
        this.anyag = anyag;
        this.megnevezes = megnevezes;
        this.megjegyzes = megjegyzes;
        this.felvitel = felvitel;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNev() {
        return this.nev;
    }

    public void setNev(String nev) {
        this.nev = nev;
    }

    public String getFilenev() {
        return this.filenev;
    }

    public void setFilenev(String filenev) {
        this.filenev = filenev;
    }

    public float getMagassag() {
        return this.magassag;
    }

    public void setMagassag(float magassag) {
        this.magassag = magassag;
    }

    public float getSzelesseg() {
        return this.szelesseg;
    }

    public void setSzelesseg(float szelesseg) {
        this.szelesseg = szelesseg;
    }

    public float getV() {
        return this.v;
    }

    public void setV(float v) {
        this.v = v;
    }

    public float getR() {
        return this.r;
    }

    public void setR(float r) {
        this.r = r;
    }

    public float getR1() {
        return this.r1;
    }

    public void setR1(float r1) {
        this.r1 = r1;
    }

    public float getR2() {
        return this.r2;
    }

    public void setR2(float r2) {
        this.r2 = r2;
    }

    public float getW() {
        return this.w;
    }

    public void setW(float w) {
        this.w = w;
    }

    public float getW1() {
        return this.w1;
    }

    public void setW1(float w1) {
        this.w1 = w1;
    }

    public float getU() {
        return this.u;
    }

    public void setU(float u) {
        this.u = u;
    }

    public float getU1() {
        return this.u1;
    }

    public void setU1(float u1) {
        this.u1 = u1;
    }

    public float getU2() {
        return this.u2;
    }

    public void setU2(float u2) {
        this.u2 = u2;
    }

    public float getZ() {
        return this.z;
    }

    public void setZ(float z) {
        this.z = z;
    }

    public float getC() {
        return this.c;
    }

    public void setC(float c) {
        this.c = c;
    }

    public float getH1() {
        return this.h1;
    }

    public void setH1(float h1) {
        this.h1 = h1;
    }

    public float getT() {
        return this.t;
    }

    public void setT(float t) {
        this.t = t;
    }

    public float getTgalfa() {
        return this.tgalfa;
    }

    public void setTgalfa(float tgalfa) {
        this.tgalfa = tgalfa;
    }

    public float getA() {
        return this.a;
    }

    public void setA(float a) {
        this.a = a;
    }

    public float getEx() {
        return this.ex;
    }

    public void setEx(float ex) {
        this.ex = ex;
    }

    public float getEy() {
        return this.ey;
    }

    public void setEy(float ey) {
        this.ey = ey;
    }

    public float getIx() {
        return this.ix;
    }

    public void setIx(float ix) {
        this.ix = ix;
    }

    public float getKx() {
        return this.kx;
    }

    public void setKx(float kx) {
        this.kx = kx;
    }

    public float getSx() {
        return this.sx;
    }

    public void setSx(float sx) {
        this.sx = sx;
    }

    public float getInx() {
        return this.inx;
    }

    public void setInx(float inx) {
        this.inx = inx;
    }

    public float getIy() {
        return this.iy;
    }

    public void setIy(float iy) {
        this.iy = iy;
    }

    public float getKy() {
        return this.ky;
    }

    public void setKy(float ky) {
        this.ky = ky;
    }

    public float getSy() {
        return this.sy;
    }

    public void setSy(float sy) {
        this.sy = sy;
    }

    public float getIny() {
        return this.iny;
    }

    public void setIny(float iny) {
        this.iny = iny;
    }

    public float getFmsuly() {
        return this.fmsuly;
    }

    public void setFmsuly(float fmsuly) {
        this.fmsuly = fmsuly;
    }

    public String getAnyag() {
        return this.anyag;
    }

    public void setAnyag(String anyag) {
        this.anyag = anyag;
    }

    public String getMegnevezes() {
        return this.megnevezes;
    }

    public void setMegnevezes(String megnevezes) {
        this.megnevezes = megnevezes;
    }

    public String getMegjegyzes() {
        return megjegyzes;
    }

    public void setMegjegyzes(String megjegyzes) {
        this.megjegyzes = megjegyzes;
    }    
    
    public Date getFelvitel() {
        return this.felvitel;
    }

    public void setFelvitel(Date felvitel) {
        this.felvitel = felvitel;
    }

    

}
