package Entities;
// Generated 2014.03.09. 21:55:51 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Tartok generated by hbm2java
 */
public class Tartoszelv  implements java.io.Serializable {


     private Integer id;
     private String projekt;
     private String tartonev;
     private float kezdes;
     private String szelveny;
     private Date felvitel;

    public Tartoszelv() {
    }

    public Tartoszelv(String projekt, String tartonev, float kezdes, String szelveny, Date felvitel) {
       this.projekt = projekt;
       this.tartonev = tartonev;
       this.kezdes = kezdes;
       this.szelveny = szelveny;
       this.felvitel = felvitel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProjekt() {
        return this.projekt;
    }
    
    public void setProjekt(String projekt) {
        this.projekt = projekt;
    }
    public String getTartonev() {
        return this.tartonev;
    }
    
    public void setTartonev(String tartonev) {
        this.tartonev = tartonev;
    }

    public float getKezdes() {
        return this.kezdes;
    }
    
    public void setKezdes(float kezdes) {
        this.kezdes = kezdes;
    }
        
    public String getSzelveny() {
        return this.szelveny;
    }
    
    public void setSzelveny(String szelveny) {
        this.szelveny = szelveny;
    }
    
    public Date getFelvitel() {
        return this.felvitel;
    }
    
    public void setFelvitel(Date felvitel) {
        this.felvitel = felvitel;
    }




}


