/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package statika;

import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duslaszlo
 */
public class drotvaz extends javax.swing.JInternalFrame {

    /**
     * Creates new form drotvaz
     */
    int UpdateQuery;
    drotvazadatok vaz = new drotvazadatok();

    public drotvaz() {
        initComponents();
        drotvazak.removeAllItems();
        drotvazak.addItem("Válassz");
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            vaz.co = DriverManager.getConnection(Global.mysql_server, Global.mysql_user, Global.mysql_password);
            vaz.st = vaz.co.createStatement();
            // A projekt nevének a beolvasása
            vaz.parancs = "SELECT distinct azonosito FROM rud order by azonosito;";
            vaz.rs = vaz.st.executeQuery(vaz.parancs);
            while (vaz.rs.next()) {
                drotvazak.addItem(vaz.rs.getString(1));
            }
            vaz.rs.close();
            vaz.st.close();
        } catch (InstantiationException e) {
        } catch (IllegalAccessException e) {
        } catch (ClassNotFoundException e) {
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        drotvazak = new javax.swing.JComboBox();
        nezet = new javax.swing.JLabel();
        drotvaz_kivalaszt = new javax.swing.JButton();
        alaphelyzet = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rudak = new javax.swing.JTable();
        rudkivalaszto = new javax.swing.JButton();
        pngkep = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Rácsos szerkezetek drótvázainak megjelenítése");
        setToolTipText("");

        jLabel1.setText("Drótváz:");

        nezet.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                nezetMouseWheelMoved(evt);
            }
        });
        nezet.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                nezetMouseDragged(evt);
            }
        });

        drotvaz_kivalaszt.setText("Kiválaszt");
        drotvaz_kivalaszt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drotvaz_kivalasztActionPerformed(evt);
            }
        });

        alaphelyzet.setText("Alaphelyzet");
        alaphelyzet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alaphelyzetActionPerformed(evt);
            }
        });

        rudak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kezdőcsp.", "Végcsp.", "Szelvény", "Kijelzés"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(rudak);

        rudkivalaszto.setText("Megjelöl");
        rudkivalaszto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rudkivalasztoActionPerformed(evt);
            }
        });

        pngkep.setText("PNG-kép");
        pngkep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pngkepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drotvazak, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drotvaz_kivalaszt)
                        .addGap(71, 71, 71)
                        .addComponent(alaphelyzet)
                        .addGap(18, 18, 18)
                        .addComponent(pngkep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rudkivalaszto)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nezet, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(drotvazak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drotvaz_kivalaszt)
                    .addComponent(alaphelyzet)
                    .addComponent(pngkep))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(rudkivalaszto))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nezet, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kepkitevo() {
        vaz.pngrajz();
        ImageIcon icon = new ImageIcon(vaz.bi);
        icon.getImage().flush();
        nezet.setIcon(icon);
        nezet.updateUI();
    }

    private void drotvaz_kivalasztActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drotvaz_kivalasztActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) rudak.getModel();
        vaz.nev = drotvazak.getSelectedItem().toString();
        vaz.adatbeolvaso();
        int j = tableModel.getRowCount();
        for (int k = 0; k < j; k++) {
            tableModel.removeRow(0);
        }
        for (int i = 1; i <= vaz.rudindex; i++) {
            String[] data = new String[3];
            data[0] = String.valueOf(vaz.rud[i][1]);
            data[1] = String.valueOf(vaz.rud[i][2]);
            data[2] = String.valueOf(vaz.rudnev[i]);
            tableModel.addRow(data);
            if (vaz.rud[i][4] == 1) {
                tableModel.setValueAt(true, i - 1, 3);
            } else {
                tableModel.setValueAt(false, i - 1, 3);
            }
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        //centerRenderer.setHorizontalAlignment(x_fok.CENTER);
        rudak.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        rudak.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        rudak.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        rudak.setAutoResizeMode(rudak.AUTO_RESIZE_OFF);
        rudak.getColumnModel().getColumn(0).setPreferredWidth(60);
        rudak.getColumnModel().getColumn(1).setPreferredWidth(60);
        rudak.getColumnModel().getColumn(2).setPreferredWidth(90);
        rudak.getColumnModel().getColumn(3).setPreferredWidth(50);
        rudak.setModel(tableModel);
        rudak.setShowGrid(true);
        kepkitevo();
    }//GEN-LAST:event_drotvaz_kivalasztActionPerformed

    private void rudkivalasztoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rudkivalasztoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) rudak.getModel();
        for (int i = 0; i < vaz.rudindex; i++) {
            //System.out.println(" javítva:" + tableModel.getValueAt(i, 3).toString());
            if (tableModel.getValueAt(i, 3).toString().equals("true")) {
                vaz.rud[i][4] = 1;
            } else {
                vaz.rud[i][4] = 0;
            }
        }
        kepkitevo();
    }//GEN-LAST:event_rudkivalasztoActionPerformed

    private void alaphelyzetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alaphelyzetActionPerformed
        // TODO add your handling code here:
        vaz.forgatas[1] = 0;
        vaz.forgatas[2] = 0;
        vaz.forgatas[3] = 0;
        kepkitevo();
    }//GEN-LAST:event_alaphelyzetActionPerformed

    private void pngkepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pngkepActionPerformed
        // TODO add your handling code here:
        vaz.pngfile();
    }//GEN-LAST:event_pngkepActionPerformed

    private void nezetMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nezetMouseDragged
        //System.out.println("X:"+evt.getX()+"  Y:"+evt.getY());
        if (SwingUtilities.isLeftMouseButton(evt)) {
            // forgatás
            if ((vaz.mx == 0) || (vaz.my == 0)) {
                vaz.mx = evt.getX();
                vaz.my = evt.getY();
            } else {
                if (evt.getX() > vaz.mx) {
                    vaz.forgatas[2]++;
                    if (vaz.forgatas[2] > 360) {
                        vaz.forgatas[2] = 0;
                    }
                    vaz.mx = evt.getX();
                }
                if (evt.getX() < vaz.mx) {
                    vaz.forgatas[2]--;
                    if (vaz.forgatas[2] < 0) {
                        vaz.forgatas[2] = 360;
                    }
                    vaz.mx = evt.getX();
                }
                if (evt.getY() > vaz.my) {
                    vaz.forgatas[3]--;
                    if (vaz.forgatas[3] < 0) {
                        vaz.forgatas[3] = 360;
                    }
                    vaz.my = evt.getY();
                }
                if (evt.getY() < vaz.my) {
                    vaz.forgatas[3]++;
                    if (vaz.forgatas[3] > 360) {
                        vaz.forgatas[3] = 0;
                    }
                    vaz.my = evt.getY();
                }
                kepkitevo();
            }
        }
        if (SwingUtilities.isRightMouseButton(evt)) {
            //mozgatás 
            if ((vaz.tx == 0) || (vaz.ty == 0)) {
                vaz.tx = evt.getX();
                vaz.ty = evt.getY();
            } else {
                if (evt.getX() > vaz.tx) {
                    vaz.kepkozep[0]++;
                    vaz.tx = evt.getX();
                }
                if (evt.getX() < vaz.tx) {
                    vaz.kepkozep[0]--;
                    vaz.tx = evt.getX();
                }
                if (evt.getY() > vaz.ty) {
                    vaz.kepkozep[1]++;
                    vaz.ty = evt.getY();
                }
                if (evt.getY() < vaz.ty) {
                    vaz.kepkozep[1]--;
                    vaz.ty = evt.getY();
                }
                kepkitevo();
            }
        }
        if (SwingUtilities.isMiddleMouseButton(evt)) {
            // Alaphelyzet visszaállítás
            vaz.kepkozep[0] = 0;
            vaz.kepkozep[1] = 0;
            vaz.forgatas[2] = 0;
            vaz.forgatas[3] = 0;
            vaz.kepnagyitas = 1;
            kepkitevo();
        }
        //System.out.println(" x_forg:"+vaz.forgatas[2]+"  y_forg:"+vaz.forgatas[3]);

    }//GEN-LAST:event_nezetMouseDragged

    private void nezetMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_nezetMouseWheelMoved
        // TODO add your handling code here:
        if (evt.getWheelRotation() < 0) {
            vaz.kepnagyitas /= 0.5;
        } else {
            vaz.kepnagyitas *= 0.5;
        }
        kepkitevo();
    }//GEN-LAST:event_nezetMouseWheelMoved
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alaphelyzet;
    private javax.swing.JButton drotvaz_kivalaszt;
    private javax.swing.JComboBox drotvazak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nezet;
    private javax.swing.JButton pngkep;
    private javax.swing.JTable rudak;
    private javax.swing.JButton rudkivalaszto;
    // End of variables declaration//GEN-END:variables
}
