/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package statika;

import Hibernate.HibernateUtil;
import java.util.List;
import javax.swing.ImageIcon;
import org.hibernate.Session;

/**
 *
 * @author SD-LEAP
 */
public class kmjell extends javax.swing.JInternalFrame {

    /**
     * Creates new form kmjell
     */
    // A változók deklarálása
    kmadatok profil = new kmadatok();
    Session session = HibernateUtil.getSessionFactory().openSession();
    String parancs;

    public kmjell() {
        initComponents();
        // A szelvények feltöltése
        session.beginTransaction();
        parancs = "select distinct megnevezes FROM Szelveny where megnevezes <> 'Összetett szelvény' order by megnevezes";
        //System.out.println(parancs);
        profil_csoport.removeAll();
        List<String> profillista = session.createQuery(parancs).list();
        for (int i = 0; i < profillista.size(); i++) {
            // A szelvénytár beolvasása
            profil_csoport.addItem(profillista.get(i));
        }
        szelvenyek_listaja.removeAll();
        parancs = "Select nev FROM Szelveny where megnevezes = '" + profillista.get(0) + "' order by nev";
        //System.out.println(parancs);
        profil.szelvenylista = session.createQuery(parancs).list();
        //szelvenyek_listaja.addItem("Válassz");
        for (int i = 0; i < profil.szelvenylista.size(); i++) {
            // A szelvénytár beolvasása
            szelvenyek_listaja.addItem(profil.szelvenylista.get(i));
        }
        session.getTransaction().commit();
        session.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        szelvenyek_listaja = new javax.swing.JComboBox();
        kivalaszto = new javax.swing.JButton();
        pngrajz = new javax.swing.JLabel();
        kmjellemzok = new javax.swing.JButton();
        pngkep = new javax.swing.JButton();
        profil_csoport = new javax.swing.JComboBox();
        profil_csoport_kivalaszto = new javax.swing.JButton();
        Kilepes = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Profilok keresztmetszeti jellemzői ");

        kivalaszto.setText("Kiválaszt");
        kivalaszto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kivalasztoActionPerformed(evt);
            }
        });

        pngrajz.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pngrajzMouseDragged(evt);
            }
        });

        kmjellemzok.setText("Km. jellemzők");
        kmjellemzok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmjellemzokActionPerformed(evt);
            }
        });

        pngkep.setText("PNG-kép");
        pngkep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pngkepActionPerformed(evt);
            }
        });

        profil_csoport_kivalaszto.setText("Profil-csoport");
        profil_csoport_kivalaszto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profil_csoport_kivalasztoActionPerformed(evt);
            }
        });

        Kilepes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/statika/exit1.png"))); // NOI18N
        Kilepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KilepesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pngrajz, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(szelvenyek_listaja, 0, 283, Short.MAX_VALUE)
                            .addComponent(profil_csoport, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(profil_csoport_kivalaszto, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(kivalaszto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kmjellemzok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pngkep, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kilepes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pngkep)
                            .addComponent(profil_csoport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profil_csoport_kivalaszto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(szelvenyek_listaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kivalaszto)
                            .addComponent(kmjellemzok)))
                    .addComponent(Kilepes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pngrajz, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kepkitevo() {
        //String szoveg;
        profil.pngrajz();
        // A PNG rajz visszaillesztése
        //szoveg = "./images/szelveny/" + profil.filenev + ".png";
        //System.out.println(" filenevbe:" + szoveg);
        ImageIcon icon = new ImageIcon(profil.bi);
        icon.getImage().flush();
        pngrajz.setIcon(icon);
        pngrajz.updateUI();
    }

    private void kivalasztoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kivalasztoActionPerformed
        // TODO add your handling code here:        
        Float meret;
        profil.nev = szelvenyek_listaja.getSelectedItem().toString();
        profil.beolvas();
        meret = Float.parseFloat(String.valueOf(Math.sqrt(Double.parseDouble(String.valueOf((profil.profil.get(0).getMagassag() / 2) * (profil.profil.get(0).getMagassag() / 2) + (profil.profil.get(0).getSzelesseg() / 2) * (profil.profil.get(0).getSzelesseg() / 2))))));
        meret *= 2;
        profil.nagyitas = 480 / meret;
        kepkitevo();
    }//GEN-LAST:event_kivalasztoActionPerformed

    private void kmjellemzokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmjellemzokActionPerformed
        // TODO add your handling code here:
        profil.keresztmetszet_szamolo(1);
        kepkitevo();
    }//GEN-LAST:event_kmjellemzokActionPerformed

    private void pngkepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pngkepActionPerformed
        // TODO add your handling code here:
        profil.pngfile();
    }//GEN-LAST:event_pngkepActionPerformed

    private void pngrajzMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pngrajzMouseDragged
        // TODO add your handling code here:
        //System.out.println("X:"+evt.getX()+"  Y:"+evt.getY());
        profil.kmkijelzes = false;
        if ((profil.mx == 0) || (profil.my == 0)) {
            profil.mx = evt.getX();
            profil.my = evt.getY();
        } else {
            if (evt.getX() < profil.mx) {
                profil.forgatas++;
                if (profil.forgatas > 360) {
                    profil.forgatas = 0;
                }
                profil.mx = evt.getX();
            }
            if (evt.getX() > profil.mx) {
                profil.forgatas--;
                if (profil.forgatas < 0) {
                    profil.forgatas = 360;
                }
                profil.mx = evt.getX();
            }
            if (evt.getY() < profil.my) {
                profil.forgatas++;
                if (profil.forgatas > 360) {
                    profil.forgatas = 0;
                }
                profil.my = evt.getY();
            }
            if (evt.getY() > profil.my) {
                profil.forgatas--;
                if (profil.forgatas < 0) {
                    profil.forgatas = 360;
                }
                profil.my = evt.getY();
            }
            kepkitevo();
        }
    }//GEN-LAST:event_pngrajzMouseDragged

    private void profil_csoport_kivalasztoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profil_csoport_kivalasztoActionPerformed
        // TODO add your handling code here:
        profil.szelvenylista.clear();
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        parancs = "Select nev FROM Szelveny where megnevezes = '" + profil_csoport.getSelectedItem() + "' order by nev";
        //System.out.println(parancs);
        profil.szelvenylista = session.createQuery(parancs).list();
        szelvenyek_listaja.removeAllItems();
        //szelvenyek_listaja.addItem("Válassz");
        for (int i = 0; i < profil.szelvenylista.size(); i++) {
            // A szelvénytár beolvasása
            //System.out.println(profil.szelvenylista.get(i));
            szelvenyek_listaja.addItem(profil.szelvenylista.get(i));
        }
        session.getTransaction().commit();
        session.close();
    }//GEN-LAST:event_profil_csoport_kivalasztoActionPerformed

    private void KilepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KilepesActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_KilepesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Kilepes;
    private javax.swing.JButton kivalaszto;
    private javax.swing.JButton kmjellemzok;
    private javax.swing.JButton pngkep;
    private javax.swing.JLabel pngrajz;
    private javax.swing.JComboBox profil_csoport;
    private javax.swing.JButton profil_csoport_kivalaszto;
    private javax.swing.JComboBox szelvenyek_listaja;
    // End of variables declaration//GEN-END:variables
}
