/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package statika;

import java.sql.*;
import javax.swing.ImageIcon;

/**
 *
 * @author SD-LEAP
 */
public class kmjell extends javax.swing.JInternalFrame {

    /**
     * Creates new form kmjell
     */
    // A változók deklarálása
    static Connection co;
    static Statement st;
    static ResultSet rs;
    kmadatok profil = new kmadatok();

    public kmjell() {
        initComponents();
        // A szelvények feltöltése
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            co = DriverManager.getConnection(Global.mysql_server, Global.mysql_user, Global.mysql_password);
            st = co.createStatement();
            // A szelvénytár beolvasása
            rs = st.executeQuery("SELECT nev FROM szelveny where megnevezes <> 'Összetett szelvény' order by nev ");
            while (rs.next()) {
                szelveny.addItem(rs.getString(1));
            }
            rs.close();
            st.close();
        } catch (InstantiationException e) {
        } catch (IllegalAccessException e) {
        } catch (ClassNotFoundException e) {
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        szelveny = new javax.swing.JComboBox();
        kivalaszto = new javax.swing.JButton();
        pngrajz = new javax.swing.JLabel();
        kmjellemzok = new javax.swing.JButton();
        pngkep = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Profilok keresztmetszeti jellemzői ");

        kivalaszto.setText("Kiválaszt");
        kivalaszto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kivalasztoActionPerformed(evt);
            }
        });

        pngrajz.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pngrajzMouseDragged(evt);
            }
        });

        kmjellemzok.setText("Km. jellemzők");
        kmjellemzok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmjellemzokActionPerformed(evt);
            }
        });

        pngkep.setText("PNG-kép");
        pngkep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pngkepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pngrajz, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(szelveny, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kivalaszto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(pngkep, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kmjellemzok, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(szelveny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kivalaszto)
                        .addComponent(pngkep))
                    .addComponent(kmjellemzok, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pngrajz, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kepkitevo() {
        //String szoveg;
        profil.pngrajz(profil.nagyitas);
        // A PNG rajz visszaillesztése
        //szoveg = "./images/szelveny/" + profil.filenev + ".png";
        //System.out.println(" filenevbe:" + szoveg);
        ImageIcon icon = new ImageIcon(profil.bi);
        icon.getImage().flush();
        pngrajz.setIcon(icon);
        pngrajz.updateUI();
    }

    private void kivalasztoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kivalasztoActionPerformed
        // TODO add your handling code here:        
        Float meret;
        profil.nev = szelveny.getSelectedItem().toString();
        profil.beolvas();
        meret = Float.parseFloat(String.valueOf(Math.sqrt(Double.parseDouble(String.valueOf((profil.magassag / 2) * (profil.magassag / 2) + (profil.szelesseg / 2) * (profil.szelesseg / 2))))));
        meret *= 2;
        profil.nagyitas = 480 / meret;
        kepkitevo();
        profil.szog = 0;
    }//GEN-LAST:event_kivalasztoActionPerformed

    private void kmjellemzokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmjellemzokActionPerformed
        // TODO add your handling code here:
        profil.keresztmetszet_szamolo(1);
        kepkitevo();
    }//GEN-LAST:event_kmjellemzokActionPerformed

    private void pngkepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pngkepActionPerformed
        // TODO add your handling code here:
        profil.pngfile();
    }//GEN-LAST:event_pngkepActionPerformed

    private void pngrajzMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pngrajzMouseDragged
        // TODO add your handling code here:
        //System.out.println("X:"+evt.getX()+"  Y:"+evt.getY());
        profil.kmkijelzes = false;
        if ((profil.mx==0) || (profil.my==0)) {
            profil.mx = evt.getX();profil.my = evt.getY();
        } else {
            if (evt.getX() < profil.mx) {
                profil.forgatas++;
                if (profil.forgatas > 360) {profil.forgatas=0;}
                profil.mx = evt.getX();
            }
            if (evt.getX() > profil.mx) {
                 profil.forgatas--;
                if (profil.forgatas < 0) {profil.forgatas=360;}
                profil.mx = evt.getX();
            }
            if (evt.getY() < profil.my) {
                profil.forgatas++;
                if (profil.forgatas > 360) {profil.forgatas=0;}
                profil.my = evt.getY();
            }
            if (evt.getY() > profil.my) {
                 profil.forgatas--;
                if (profil.forgatas < 0) {profil.forgatas=360;}
                profil.my = evt.getY();
            }
            kepkitevo();
        }
    }//GEN-LAST:event_pngrajzMouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton kivalaszto;
    private javax.swing.JButton kmjellemzok;
    private javax.swing.JButton pngkep;
    private javax.swing.JLabel pngrajz;
    private javax.swing.JComboBox szelveny;
    // End of variables declaration//GEN-END:variables
}
