/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * projekt.java
 *
 * Created on 2012.12.27., 12:38:33
 */
package statika;

import Entities.Projectek;
import Hibernate.HibernateUtil;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import java.util.Date;

/**
 *
 * @author SD-LEAP
 */
public class projekt extends javax.swing.JInternalFrame {

    /**
     * Creates new form projekt
     */
    String megnevezes = "";
    String parancs;
    Date now = new Date();
    static Connection co;
    static Statement st;
    static ResultSet rs;

    public projekt() {
        initComponents();
        // A scheduler-ek beolvasása Mysql
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            co = DriverManager.getConnection(Global.mysql_server, Global.mysql_user, Global.mysql_password);
            st = co.createStatement();
            parancs = "SELECT projekt from Projectek Where aktiv = '1'";
            //System.out.println("SQL: " + parancs);
            rs = st.executeQuery(parancs);
            while (rs.next()) {
                megnevezes = rs.getString("projekt");
            }
            //System.out.println("Projekt:" + megnevezes);
            parancs = "SELECT projekt from Projectek order by projekt";
            //System.out.println("SQL: " + parancs);
            rs = st.executeQuery(parancs);
            while (rs.next()) {
                Projectek c = new Projectek();
                c.setProjekt(rs.getString("projekt"));
                Projectlista.addItem(c.getProjekt());
            }
            rs.close();
            st.close();
        } catch (InstantiationException e) {
        } catch (IllegalAccessException e) {
        } catch (ClassNotFoundException e) {
        } catch (SQLException e) {
        }

        parancs = "FROM Projectek Where aktiv = '1'";

        projekt.setText(megnevezes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ujprojekt = new javax.swing.JTextField();
        Ujproject_letrehozas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        projeckt_kivalasztas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        projekt = new javax.swing.JTextField();
        megrendelo = new javax.swing.JTextField();
        ujleiras = new javax.swing.JTextField();
        Projectlista = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Projekt-beállítás");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Új projekt létrehozása:");

        Ujproject_letrehozas.setText("Létrehozás");
        Ujproject_letrehozas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ujproject_letrehozasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Meglévő projekt:");

        projeckt_kivalasztas.setText("Kiválasztás");
        projeckt_kivalasztas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projeckt_kivalasztasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("A beállított projekt:");

        projekt.setEditable(false);
        projekt.setText("Beállított projekt");
        projekt.setBorder(null);

        jLabel4.setText("Projektnév:");

        jLabel5.setText("Megrendelő:");

        jLabel6.setText("Projekt-leírás:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/statika/exit1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(4, 4, 4))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projekt, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projeckt_kivalasztas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(Projectlista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(megrendelo, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addComponent(ujleiras, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addComponent(Ujproject_letrehozas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ujprojekt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ujprojekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(megrendelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ujleiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ujproject_letrehozas))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(projeckt_kivalasztas)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Projectlista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ujproject_letrehozasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ujproject_letrehozasActionPerformed
        // TODO add your handling code here:

        Projectek ujproject = new Projectek();
        if (ujprojekt.getText().length() > 0) {
            // Az aktív projekt kikapcsolása
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            parancs = "update Projectek set aktiv = '0' where aktiv = '1'";
            Query query = session.createQuery(parancs);
            int result = query.executeUpdate();
            ujproject.setProjekt(ujprojekt.getText());
            ujproject.setLeiras(ujleiras.getText());
            ujproject.setMegrendelo(megrendelo.getText());
            ujproject.setAktiv("1");
            ujproject.setFelvitel(now);
            session.save(ujproject);
            projekt.setText(ujprojekt.getText());
            // A beírt adatok törlése
            ujprojekt.setText("");
            megrendelo.setText("");
            ujleiras.setText("");
            // A jComboBox1 újrafeltöltése            
            Projectlista.removeAllItems();
            //session.beginTransaction();
            parancs = "FROM Projectek order by projekt";
            //System.out.println(parancs);
            List<Projectek> projectek = session.createQuery(parancs).list();
            for (int i = 0; i < projectek.size(); i++) {
                Projectlista.addItem(projectek.get(i).getProjekt());
            }
            session.getTransaction().commit();
            session.close();
        }
    }//GEN-LAST:event_Ujproject_letrehozasActionPerformed

    private void projeckt_kivalasztasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projeckt_kivalasztasActionPerformed
        // Az aktív projekt kikapcsolása
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        parancs = "update Projectek set aktiv = '0' where aktiv = '1'";
        Query query = session.createQuery(parancs);
        int result = query.executeUpdate();
        parancs = "update Projectek set aktiv = '1' where projekt='";
        parancs = parancs + Projectlista.getSelectedItem().toString() + "'";
        query = session.createQuery(parancs);
        result = query.executeUpdate();
        session.getTransaction().commit();
        session.close();
        projekt.setText(Projectlista.getSelectedItem().toString());
    }//GEN-LAST:event_projeckt_kivalasztasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Projectlista;
    private javax.swing.JButton Ujproject_letrehozas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField megrendelo;
    private javax.swing.JButton projeckt_kivalasztas;
    private javax.swing.JTextField projekt;
    private javax.swing.JTextField ujleiras;
    private javax.swing.JTextField ujprojekt;
    // End of variables declaration//GEN-END:variables
}
